// Dados da Equipe de TI
const tiData = [
    { cotec: "COTEC -MARIA SEBASTIANA DA SILVA", cidade: "PORANGATU-GO", telefone: "(62)9 9925-6161", nome: "JOÃO ANDRÉ ALVES CARVALHO", horario: "07:00 -11:30 / 13:30 -17:00 - Sábado 08:00 ás 12:00" },
    { cotec: "COTEC - AGUINALDO CAMPOS NETO", cidade: "CATALÃO-GO", telefone: "(64) 9 8421-0755", nome: "AGUINALDO DA SILVEIRA", horario: "13:00 - 17:00 / 18:00 - 22:00 - Sábado 08:00 às 12:00" },
    { cotec: "COTEC - CELIO DOMINGOS MAZZONETTO", cidade: "CERES-GO", telefone: "(62)99641-2381", nome: "WALTER JUNIOR JOVENCIO DE FARIA", horario: "08:00-11:00 / 13:00 - 18:00 - Sábado 08:00 às 12:00" },
    { cotec: "COTEC - LUIZ HUMBERTO DE MENEZES", cidade: "SANTA HELENA DE GOIAS - GO", telefone: "(64) 9 9270-1291", nome: "MOUZER DA SILVA", horario: "" },
    { cotec: "COTEC - GOVERNADOR ONOFRE QUINAN", cidade: "ANÁPOLIS", telefone: "(62) 99664-6382", nome: "JEBBERSON MOURA DA COSTA", horario: "13:00 - 17:00 / 18:00 - 22:00 - Sábado 08:00 as 12:00" },
    { cotec: "COTEC - GOVERNADOR ONOFRE QUINAN", cidade: "ANÁPOLIS", telefone: "(62) 99115-1803", nome: "DIEGO DOS SANTOS MACHADO", horario: "08:00 - 12:00 / 13:00 - 17:00 - Sábado 08:00 as 12:00" },
    { cotec: "COTEC - SEBASTIÃO DE SIQUEIRA", cidade: "GOIÂNIA - GO", telefone: "(62) 9 8188-1083", nome: "JAILTON CARVALHO FELIX", horario: "" },
    { cotec: "COTEC - RUTH VILAÇA CORREIA LEITE CARDOSO", cidade: "CAIAPÔNIA - GO", telefone: "(64) 99963-0129", nome: "WAGTON RODRIGUES SOUSA", horario: "13:00 - 17:00 / 18:00 - 22:00 - Sábado 08:00 às 12:00" },
    { cotec: "COTEC - GOVERNADOR OTÁVIO LAGE", cidade: "GOIANÉSIA", telefone: "(62) 98403-6513", nome: "EDUARDO JOSÉ MAGALHÃES", horario: "07:00 - 11:00 / 13:00 - 17:00 - Sábado 08:00 às 12:00" },
    { cotec: "COTEC - CELSO MONTEIRO FURTADO", cidade: "URUANA - GO", telefone: "(62) 98447-7408", nome: "THALLES HENRIQUE PIRES MACHADO", horario: "08:00 - 12:00 / 14:00 - 18:00 - Sábado 08:00 / 12:00" },
    { cotec: "COTEC - JERÔNIMO CARLOS DO PRADO", cidade: "GOIATUBA - GO", telefone: "(64) 99223-8723", nome: "ALEX ANTÔNIO DOS SANTOS", horario: "08:00 - 11:00 / 13:00 - 18:00 - Sábado 08:00 AS 12:00" },
    { cotec: "COTEC - JERÔNIMO CARLOS DO PRADO", cidade: "GOIATUBA - GO", telefone: "(64) 98452-0286", nome: "JULY HONORATO", horario: "13:00 - 17:00 / 18:00 - 22:00 - Sábado 08:00 AS 12:00" },
    { cotec: "COTEC - GOIADIRA AYRES DO COUTO", cidade: "GOIÁS-GO", telefone: "(62)99671-2955", nome: "DANYEL ARRAIS", horario: "08:00 - 12:00 / 13:00 - 17:00" },
    { cotec: "COTEC - IRTES ALVES DE CASTRO RIBEIRO", cidade: "JARAGUÁ - GO", telefone: "(62) 9 84022864", nome: "EGUIMAR AZEVEDO DA SILVA", horario: "08:00-12:00 / 14:00 - 18:00" },
    { cotec: "COTEC - IRTES ALVES DE CASTRO RIBEIRO", cidade: "JARAGUÁ - GO", telefone: "(62) 9 85304639", nome: "MAYARA DIAS PEREIRA", horario: "08:00-12:00 / 14:00 - 18:00" },
    { cotec: "COTEC - PADRE ANTONIO VERMEY", cidade: "PALMEIRAS DE GOIAS-GO", telefone: "(64) 9 9223-0312", nome: "AGNALDO FELICIO DE CARVALHO FILHO", horario: "13:00-17:00/ 17:00-18:00 - Sábado 08:00 as 12:00" },
    { cotec: "COTEC - GENERVINO EVANGELISTA DA FONSECA", cidade: "CRISTALINA - GO", telefone: "(61) 9 9938-2647", nome: "AGNALDO BARROS RIBEIRO DOS SANTOS", horario: "08:00-12:00/ 18:00 - 22:00 - Sábado 08:00 as 12:00" },
    { cotec: "", cidade: "FORMOSA - GO", telefone: "", nome: "", horario: "" }
];

// Dados de Impressoras
const impressorasData = [
    { cotec: "COTEC -MARIA SEBASTIANA DA SILVA", cidade: "PORANGATU-GO", monocromatica: "3", policromatica: "1", funcionando: "SIM", obs: "1 impressora do colegio" },
    { cotec: "COTEC - AGUINALDO CAMPOS NETO", cidade: "CATALÃO-GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADA" },
    { cotec: "COTEC - CELIO DOMINGOS MAZZONETTO", cidade: "CERES-GO", monocromatica: "5", policromatica: "1", funcionando: "SIM", obs: "3 impressoras do colégio" },
    { cotec: "COTEC - LUIZ HUMBERTO DE MENEZES", cidade: "SANTA HELENA DE GOIAS - GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "" },
    { cotec: "COTEC - GOVERNADOR ONOFRE QUINAN", cidade: "ANÁPOLIS", monocromatica: "4", policromatica: "1", funcionando: "SIM", obs: "2 Impressoras da escola" },
    { cotec: "COTEC - SEBASTIÃO DE SIQUEIRA", cidade: "GOIÂNIA", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "2 Impressoras do Colégio" },
    { cotec: "COTEC - RUTH VILAÇA CORREIA LEITE CARDOSO", cidade: "CAIAPÔNIA - GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - GOVERNADOR OTÁVIO LAGE", cidade: "GOIANÉSIA", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - CELSO MONTEIRO FURTADO", cidade: "URUANA - GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - JERÔNIMO CARLOS DO PRADO", cidade: "GOIATUBA - GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - GOIADIRA AYRES DO COUTO", cidade: "GOIÁS-GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - IRTES ALVES DE CASTRO RIBEIRO", cidade: "JARAGUÁ - GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - PADRE ANTONIO VERMEY", cidade: "PALMEIRAS DE GOIAS -GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" },
    { cotec: "COTEC - GENERVINO EVANGELISTA DA FONSECA", cidade: "CRISTALINA - GO", monocromatica: "2", policromatica: "1", funcionando: "SIM", obs: "LOCADAS" }
];

// Dados de Internet
const internetData = [
    { cotec: "COTEC -MARIA SEBASTIANA DA SILVA", cidade: "PORANGATU-GO", velocidadeLink: "2 PONTOS -500 GB", operadora: "VIVO -TERRA - FIBRA", speedtest: "800.77-Download Mbps - 302.09 Upload Mbps", obs: "REDE CONECTA" },
    { cotec: "COTEC - AGUINALDO CAMPOS NETO", cidade: "CATALÃO-GO", velocidadeLink: "1 GB", operadora: "TEK TURBO", speedtest: "936.82 DOWN - 445.88 UPLOAD", obs: "" },
    { cotec: "COTEC - LUIZ HUMBERTO DE MENEZES", cidade: "SANTA HELENA DE GOIAS - GO", velocidadeLink: "500 MB", operadora: "NETFRIBRA", speedtest: "519 D - 372 UP", obs: "REDE CONECTA" },
    { cotec: "COTEC - SEBASTIÃO DE SIQUEIRA", cidade: "GOIÂNIA", velocidadeLink: "1 GB", operadora: "LINQ TELECOM", speedtest: "", obs: "" },
    { cotec: "COTEC - RUTH VILAÇA CORREIA LEITE CARDOSO", cidade: "CAIAPÔNIA - GO", velocidadeLink: "1 GB", operadora: "FIBERNET", speedtest: "823.77 DOWNLOAD - 475.32 UPLOAD", obs: "" },
    { cotec: "COTEC - GOVERNADOR OTÁVIO LAGE", cidade: "GOIANÉSIA", velocidadeLink: "1 GIGA", operadora: "INFOTECH", speedtest: "657.53-Dow Mbps | 465.89 Up Mbps", obs: "" },
    { cotec: "COTEC - CELSO MONTEIRO FURTADO", cidade: "URUANA - GO", velocidadeLink: "1 GB", operadora: "GIGABYTE", speedtest: "905,7 - DOWNLOAD / 502,2 - UPLOAD", obs: "" },
    { cotec: "COTEC - JERÔNIMO CARLOS DO PRADO", cidade: "GOIATUBA - GO", velocidadeLink: "2 LINKS - 800 GB", operadora: "CLICK TURBO", speedtest: "650 DOWN - 500 UPLOAD", obs: "" },
    { cotec: "COTEC - GOIADIRA AYRES DO COUTO", cidade: "GOIÁS-GO", velocidadeLink: "1 GB", operadora: "AERO REDE", speedtest: "880.70 Download / 412.14 Upload", obs: "REDE CONECTA" },
    { cotec: "COTEC - IRTES ALVES DE CASTRO RIBEIRO", cidade: "JARAGUÁ - GO", velocidadeLink: "1 GB", operadora: "GIGA BYTE", speedtest: "900 MB", obs: "" },
    { cotec: "COTEC - CELIO DOMINGOS MAZZONETTO", cidade: "CERES - GO", velocidadeLink: "900 MB", operadora: "GIGABYTE", speedtest: "850 DOWNLOAD / 470 UPLOAD", obs: "" },
    { cotec: "COTEC- PADRE ANTONIO VERMEY", cidade: "PALMEIRAS DE GOIAS-GO", velocidadeLink: "2 LINKS- 800 MB", operadora: "ONLINE", speedtest: "782 DOWNLOAD / 736 UPLOAD", obs: "REDE CONECTA" },
    { cotec: "COTEC - GENERVINO EVANGELISTA DA FONSECA", cidade: "CRISTALINA - GO", velocidadeLink: "1 GB", operadora: "NETIX", speedtest: "880 DOWNLOAD / 880 UPLOAD", obs: "" }
];

// Dados de Equipamentos
const equipamentosData = [
    { cotec: "COTEC -MARIA SEBASTIANA DA SILVA", cidade: "PORANGATU-GO", equipamentos: "2 ALICATE DE CRIMPAR, 3 ALICATES DE CORTE 1 ALICATES DE BICO, 6 CHAVES FILIPS, 7 CHAVES DE FENDA, 1 MULTMETRO, 1 FERRO DE SOLDA, 1 TESTADOR DE CABO, 4 PENDRIVE ,1 HD EXTERNO.", unifi: "6 UNIFI" },
    { cotec: "COTEC - LUIZ HUMBERTO DE MENEZES", cidade: "SANTA HELENA DE GOIAS - GO", equipamentos: "1 ALICATE DE CRIMPAR, 4 ALICATES DE CORTE, 1 ALICATE, 1 ALICATES DE BICO, 3 CAHVES FILIPS, 5 CAHVES DE FENDA, 1 MULTIMETRO, 1 FERRO DE SOLDA, 1 TESTADOR DE CABO, 6 PENDRIVE, 1 HD EXTERNO", unifi: "6 UNI FI" },
    { cotec: "COTEC SEBASTIÃO DE SIQUEIRA", cidade: "GOIÂNIA - GO", equipamentos: "2 CHAVES DE FENDA, 2 CHAVES FILIPS, 1 TESTADOR DE REDE, 4 ALICATES DE CRIMPAR, 1 FERRO DE SOLDA, 1 MULTIMETRO", unifi: "" },
    { cotec: "COTEC - RUTH VILAÇA CORREIA LEITE CARDOSO", cidade: "CAIAPÔNIA - GO", equipamentos: "1 HD EXTERNO 2 TB – KROSSELEGANCE, 1 TESTADOR DE CABO DE REDE – BOMVINK, 1 MULTIMETRO DIGITAL – THOMPSON, 1 LOCALIZADOR DE CABOS – EXBOM, 1 ALICATE DE CRIMPAR RJ45/RJ11/RJ12 – BOMVINK, 2 KIT CHAVES STANLEY, 2 LIMPA CONTATO MP80 MUNDIAL PRIME, 9 BATERIAS LÍTIO 3V CR2032, 80 CONECTORES RJ45 CAT6 - INTELBRAS, 2 PENDRIVES 32 GB – KINGSTON, 6 CHAVES DE FENDA, 4 CHAVES PHILIPS, 1 FERRO DE SOLDA, 3 PUNCH DOWN, 1 ALICATE UNIVERSAL, 1 ALICATE DE BICO, 2 ALICATES DE CORTE DIAGONAL", unifi: "7 UNIFI" },
    { cotec: "COTEC - GOVERNADOR OTÁVIO LAGE", cidade: "GOIANÉSIA", equipamentos: "4 - ALICATE BICO MEIA CANA, 2 - ALICATE DE CORTE DIAGONAL, 2 - ALICATE UNIVERSAL, 3 - ALICATE PUNCH DOWN, 1 - ALICATE DECAPADOR, 2 - PARAFUSADEIRAS A BATERIA, 7 - PEN-DRIVE, 1 - HD EXTERNO, 2 - JOGO DE CHAVES PRECISÃO 6 PCS, 10 - CHAVE DE FENDA, 6 - CHAVE PHILIPS, 1 - JOGO DE CHAVES ALLEN, 2 - ALICATE DE CRIMPAR, 1 - TESTADOR DE CABOS, 1 - MULTÍMETRO DIGITAL, 1 - FERRO DE SOLDA, 1 - PASSADOR DE FIOS 20M COM ALMA DE AÇO, 1 - PENTE DE CABOS ORGANIZADOR CAT.5E/CAT.6, 1 - FERRAMENTA PARA FIXAÇÃO E REMOÇÃO DE PORCA GAIOLA M5 OU M6, 1 - BOLSA FERRAMENTAS FUNDO EMBORRACHADO 24 COMPARTIMENTOS LOTUS", unifi: "7 UNIFI" },
    { cotec: "COTEC - CELSO MONTEIRO FURTADO", cidade: "URUANA - GO", equipamentos: "3 ALICATES DE CRIMPAGEM, 3 ALICATES PUNCH DOWN, 1 ALICATE DE CRIMPAGEM E DECAPAGEM, 1 ALICATE UNIVERSAL, 1 ALICATE DE BICO, 2 ALICATES DE CORTE, 1 PCT 60 CONECTORES MACHO RJ45 CAT6, 5 CONECTORES FÊMEA RJ45 CAT6, 2 TESTADORES DE CABO, 1 TESTADOR E LOCALIZADOR DE CABOS, 1 CX DE CABO PAR-TRANÇADO CAT6, JOGO DE CHAVES PHILLIPS, JOGO DE CHAVES DE FENDA, 2 JOGOS DE CHAVES DE FENDA DE PRECISÃO, 10 BATERIAS CR2032, 1 FITA ISOLANTE, 1 LIMPA-CONTATO SPRAY, 1 FERRO DE SOLDA (SEM ESTANHO), 1 HD EXTERNO 500GB, 1 HD EXTERNO 2TB, 15 PEN-DRIVE 4GB, 4 WEBCAM", unifi: "4 UNIFI" },
    { cotec: "COTEC - JERÔNIMO CARLOS DO PRADO", cidade: "GOIATUBA - GO", equipamentos: "2 - ALICATE BICO, 2 - ALICATE PUNCH DOWN, 2 - PEN-DRIVE, 1 - JOGO CHAVE PHILIPS, 1 - ALICATE DE CRIMPAR, 1 - TESTADOR DE CABOS, 1 - MULTÍMETRO DIGITAL, 1 - FERRO DE SOLDA", unifi: "7 UNIFI" },
    { cotec: "COTEC - GOIADIRA AYRES DO COUTO", cidade: "GOIÁS-GO", equipamentos: "01 - ALICATE UNIVERSAL, 01 - ALICATE DE BICO, 01 - ALICATE DE CORTE, 01 - ALICATE PUNCH DOWN, 01 - PEN-DRIVE, 02 - JOGO CHAVE PHILIPS, 02 - ALICATE DE CRIMPAR, 01 - TESTADOR DE CABOS, 01 - LOCALIZADOR DE CABOS, 01 - FERRO DE SOLDA, 01 - SOPRADOR, 01 - ESTILETE", unifi: "10 UNIFI" },
    { cotec: "COTEC - GOVERNADOR ONOFRE QUNIAN", cidade: "ANÁPOLIS", equipamentos: "02 - ALICATE UNIVERSAL, 02 - ALICATE DE BICO, 02 - ALICATE DE CORTE, 02 - PEN-DRIVE (32GB), 01 – HD EXTERNO (1TB), 01 – MULTÍMETRO, 02 – PUNCH DOWN, 01 - JOGO CHAVE PHILIPS, 02 - ALICATE DE CRIMPAR, 01 - TESTADOR DE CABOS, 01 - LOCALIZADOR DE CABOS, 01 - FERRO DE SOLDA, 01 - SOPRADOR, 01 - ESTILETE, 01 – DECAPADOR DE CABOS", unifi: "6" },
    { cotec: "COTEC - IRTES ALVES DE CASTRO RIBEIRO", cidade: "JARAGUÁ - GO", equipamentos: "1 ALICATES DE CRIMPAGEM, 1 ALICATES PUNCH DOWN, 1 ALICATE DE DECAPAGEM, 1 ALICATE UNIVERSAL, 1 ALICATE DE BICO, 2 ALICATES DE CORTE, 10 CONECTORES FÊMEA RJ45 CAT6, 1 TESTADORES DE CABO, 1 TESTADOR E LOCALIZADOR DE CABOS, 1 CX DE CABO PAR-TRANÇADO CAT6, JOGO DE CHAVES PHILLIPS, 1 CHAVE DE FENDA, 2 JOGOS DE CHAVES DE FENDA DE PRECISÃO, 50 BATERIAS CR2032, 1 FITA ISOLANTE, 1 LIMPA-CONTATO SPRAY, 1 FERRO DE SOLDA (SEM ESTANHO), 2 PEN-DRIVE 32GB, 1 ESTILETE, 1 FERRO DE SOLDA", unifi: "3 UNIFI" },
    { cotec: "COTEC - CELIO DOMINGOS MAZZONETTO", cidade: "CERES - GO", equipamentos: "7 CHAVES DE FENDA, 6 CHAVES PHILIPS, 1 TESTADOR DE CABO, 1 ALICATE, 1 ALICATE DE CORTE, 3 ALICATE DE CRIMPAR, 3 HD EXTERNO, 1 PENDRIVE, 1 PINCEL, 2 ESTILETE, 1 KIT CHAVE DE PRECISÃO, 2 ALICATE PUNCH DOWN, 1 PASSA FIO, 2 ALICATE DE DESCASCAR FIO, 1 MULTIMETRO", unifi: "4 UNIFI" },
    { cotec: "COTEC - PADRE ANTONIO VERMEY", cidade: "PALMEIRAS DE GOIAS-GO", equipamentos: "2 ALICATES DE CRIMPAR, 1 HD EXTERNO, 2 ALICATES DE CORTE, 1 MULTIMETRO, 2 ALICATES PUNCH DOWN, 3 PEN DRIVE, 1 JOGO DE CHAVE NORMAL, 2 ALICATE DE DESCASCAR FIO, 1 FERRO DE SOLDA", unifi: "4 UNIFI" },
    { cotec: "COTEC - AGUINALDO CAMPOS NETO", cidade: "CATALÃO-GO", equipamentos: "03 ALICATE UNIVERSAL, 01 ALICATE CORTE, 01 ALICATE BICO, 02 ALICATE DECAPADOR, 05 ALICATE CRIMPAGEM, 03 CHAVE FENDA, 01 CHAVE FENDA TESTE FASE, 04 CHAVE PHILIPS, 01 ESTILETE, 01 JOGO CHAVE DE PRECISAO PHILIPS STANLEY C/6, 01 PUNCH DOWN, 02 PENDRIVE 64GB, 02 HD EXTERNO 2 TB", unifi: "3" }
];

// Dados de Emails Corporativos
const emailsData = [
    { id: "1", nome: "Gabriel Felipe Correa Gomes", cpf: "07802618100", emailPessoal: "gfcggabrielcorrea@gmail.com", emailCorporativo: "gabriel.gomes@goias.gov.br", status: "criado" },
    { id: "2", nome: "Iara Lyssa Nunes Dias", cpf: "02530407100", emailPessoal: "lyssnunes@gmail.com", emailCorporativo: "iara.dias@goias.gov.br", status: "criado" },
    { id: "3", nome: "Adriana Gomes Bezerra Martins", cpf: "43042341100", emailPessoal: "adrianagbezerra@hotmail.com", emailCorporativo: "adriana.bmartins@goias.gov.br", status: "criado" },
    { id: "4", nome: "Ana Flavia Bueno de Souza", cpf: "420015108", emailPessoal: "aninhavitoriabvalentina@gmail.com", emailCorporativo: "ana.bdsouza@goias.gov.br", status: "criado" },
    { id: "5", nome: "Ana Lidia de Sousa Gomes", cpf: "1689160101", emailPessoal: "analidiasouza55@gmail.com", emailCorporativo: "ana.lsgomes@goias.gov.br", status: "criado" },
    { id: "6", nome: "Ana Paula de Aguiar Berger", cpf: "5865281640", emailPessoal: "anapaula.berger@gmail.com", emailCorporativo: "ana.berger@goias.gov.br", status: "criado" },
    { id: "7", nome: "Angelica Perez Goulart", cpf: "94067422172", emailPessoal: "angelica_pgoulart@hotmail.com", emailCorporativo: "angelica.goulart@goias.gov.br", status: "criado" },
    { id: "8", nome: "Bruno Jose Ferreira Freitas", cpf: "70298307170", emailPessoal: "freitasb80@gmail.com", emailCorporativo: "bruno.ffreitas@goias.gov.br", status: "criado" },
    { id: "9", nome: "Danilo Alves de Lima", cpf: "1036571181", emailPessoal: "daniloalves2005@gmail.com", emailCorporativo: "danilo.adlima@goias.gov.br", status: "criado" },
    { id: "10", nome: "Darlene Viana de Santana Mendes", cpf: "1037734106", emailPessoal: "darlenevsmendes@gmail.com", emailCorporativo: "darlene.mendes@goias.gov.br", status: "criado" },
    { id: "11", nome: "Dayane Cabral Araujo Ribeiro", cpf: "97966398153", emailPessoal: "day.cabral@hotmail.com", emailCorporativo: "dayane.aribeiro@goias.gov.br", status: "criado" },
    { id: "12", nome: "Deidiane Teixeira de Macedo", cpf: "1133734146", emailPessoal: "deidiane.macedo5@gmail.com", emailCorporativo: "deidiane.macedo@goias.gov.br", status: "criado" },
    { id: "13", nome: "Dina Sonia de Queiroz", cpf: "38078317115", emailPessoal: "dinaqueiroz@msn.com", emailCorporativo: "dina.queiroz@goias.gov.br", status: "criado" },
    { id: "14", nome: "Dirceu Manoel de Almeida Junior", cpf: "58476377134", emailPessoal: "dirceujunior2014@gmail.com", emailCorporativo: "dirceu.almeida@goias.gov.br", status: "criado" },
    { id: "15", nome: "Edna Lemes Martins Pereira", cpf: "45154848187", emailPessoal: "ednapgtu1@gmail.com", emailCorporativo: "edna.mpereira@goias.gov.br", status: "criado" },
    { id: "16", nome: "Elaine Alves de Almeida", cpf: "470463171", emailPessoal: "elaine.wjf@gmail.com", emailCorporativo: "elaine.aalmeida@goias.gov.br", status: "criado" },
    { id: "17", nome: "Elis Cristina da Silva Pereira", cpf: "75524317172", emailPessoal: "eliscristinasilva09@gmail.com", emailCorporativo: "elis.pereira@goias.gov.br", status: "criado" },
    { id: "18", nome: "Elisete Resende Souza Yamabe", cpf: "83595414187", emailPessoal: "lizayamabe@gmail.com", emailCorporativo: "elisete.yamabe@goias.gov.br", status: "criado" },
    { id: "19", nome: "Ellen Caetano de Oliveira Borges", cpf: "300389108", emailPessoal: "ellencaetano@hotmail.com", emailCorporativo: "ellen.borges@goias.gov.br", status: "criado" },
    { id: "20", nome: "Fânia Borges Santos", cpf: "97248347604", emailPessoal: "faniaborges10@gmail.com", emailCorporativo: "fania.santos@goias.gov.br", status: "criado" },
    { id: "21", nome: "Flavio Antonio Barbosa Neves", cpf: "95079890134", emailPessoal: "fbn.antonio@gmail.com", emailCorporativo: "flavio.neves@goias.gov.br", status: "criado" },
    { id: "22", nome: "Geisiane Rosa da Silva Magalhaes", cpf: "88850676115", emailPessoal: "geisianemagalhaes@hotmail.com", emailCorporativo: "geisiane.magalhaes@goias.gov.br", status: "criado" },
    { id: "23", nome: "Geovani Corcino dos Santos", cpf: "2714242146", emailPessoal: "geovanicorcino@professorept.com", emailCorporativo: "geovani.csantos@goias.gov.br", status: "criado" },
    { id: "24", nome: "Glaucia Matias dos Santos", cpf: "95063102115", emailPessoal: "glauciamatias25@gmail.com", emailCorporativo: "glaucia.santos@goias.gov.br", status: "criado" },
    { id: "25", nome: "Ismael César Nogueira da Abadia", cpf: "62985669400", emailPessoal: "bobnooguer@gmail.com", emailCorporativo: "ismael.nogueira@goias.gov.br", status: "criado" },
    { id: "26", nome: "Ivone Arruda Ribeiro", cpf: "24318361187", emailPessoal: "ivonearrudaribeiro@hotmail.com", emailCorporativo: "ivone.ribeiro@goias.gov.br", status: "criado" },
    { id: "27", nome: "Joarina Novantino dos Santos", cpf: "99981661104", emailPessoal: "joarina@hotmail.com", emailCorporativo: "joarina.santos@goias.gov.br", status: "criado" },
    { id: "28", nome: "Karla Brenda Costa Goncalves El Homsi", cpf: "36088650125", emailPessoal: "karla.brenda@live.com", emailCorporativo: "karla.homsi@goias.gov.br", status: "criado" },
    { id: "29", nome: "Karolyne Stephany Leite", cpf: "70117394165", emailPessoal: "karolynestephany@gmail.com", emailCorporativo: "karolyne.leite@goias.gov.br", status: "criado" },
    { id: "30", nome: "Kelly Alves dos Anjos", cpf: "66416108", emailPessoal: "kellyanjos31@gmail.com", emailCorporativo: "kelly.martins@goias.gov.br", status: "criado" },
    { id: "31", nome: "Leidynara Fatima Porto", cpf: "2462495139", emailPessoal: "leidy.porto@outlook.com", emailCorporativo: "leidynara.porto@goias.gov.br", status: "criado" },
    { id: "32", nome: "Lia Pinto Cunha Borges dos Santos", cpf: "85685780125", emailPessoal: "liapcbs2@gmail.com", emailCorporativo: "lia.santos@goias.gov.br", status: "criado" },
    { id: "33", nome: "Luana Cristina Alkmim Reis", cpf: "6797614627", emailPessoal: "luakar1984@gmail.com", emailCorporativo: "luana.areis@goias.gov.br", status: "criado" },
    { id: "34", nome: "Luiz Jose Marques de Faria Junior", cpf: "1774708108", emailPessoal: "luizfsa23@gmail.com", emailCorporativo: "luiz.faria@goias.gov.br", status: "criado" },
    { id: "35", nome: "Magno da Costa Lima", cpf: "2307893156", emailPessoal: "limmamagno@gmail.com", emailCorporativo: "magno.clima@goias.gov.br", status: "criado" },
    { id: "36", nome: "Marcia Dias de Lima", cpf: "96585382153", emailPessoal: "marciadiasdelima@outlook.com", emailCorporativo: "marcia.dlima@goias.gov.br", status: "criado" },
    { id: "37", nome: "Marilene Barbosa Nunes Duarte", cpf: "3962021604", emailPessoal: "mariduartenunes@outlook.com", emailCorporativo: "marilene.duarte@goias.gov.br", status: "criado" },
    { id: "38", nome: "Marilia Toledo Espindola", cpf: "83258833168", emailPessoal: "mariliatoledo26@hotmail.com", emailCorporativo: "marilia.espindola@goias.gov.br", status: "criado" },
    { id: "39", nome: "Marluce Alves da Silva", cpf: "43882072172", emailPessoal: "alvesilva.marluce@gmail.com", emailCorporativo: "marluce.silva@goias.gov.br", status: "criado" },
    { id: "40", nome: "Michelle Aparecida Machado", cpf: "3071050160", emailPessoal: "michelle.machado.cotec@gmail.com", emailCorporativo: "michelle.machado@goias.gov.br", status: "criado" },
    { id: "41", nome: "Mizael Vaz Crisostomo Peixoto", cpf: "70037802160", emailPessoal: "mizaelvcp@gmail.com", emailCorporativo: "mizael.peixoto@goias.gov.br", status: "criado" },
    { id: "42", nome: "Nayane Junqueira Duarte Faria", cpf: "1144407192", emailPessoal: "nayanejunqueira@hotmail.com", emailCorporativo: "nayane.dfaria@goias.gov.br", status: "criado" },
    { id: "43", nome: "Nilvania de Santana Scalabrini", cpf: "88442837191", emailPessoal: "marciadiasdelima@outlook.com", emailCorporativo: "nilvania.scalabrini@goias.gov.br", status: "criado" },
    { id: "44", nome: "Paula Leticia Gouveia Santana Castro", cpf: "5010367173", emailPessoal: "paulaleticiags@hotmail.com", emailCorporativo: "paula.scastro@goias.gov.br", status: "criado" },
    { id: "45", nome: "Rita Aparecida da Silva", cpf: "33256047149", emailPessoal: "ritinha.aparecida@hotmail.com", emailCorporativo: "rita.adsilva@goias.gov.br", status: "criado" },
    { id: "46", nome: "Rogelina Ferreira Machado", cpf: "1535703180", emailPessoal: "rogelina_fm@hotmail.com", emailCorporativo: "rogelina.machado@goias.gov.br", status: "criado" },
    { id: "47", nome: "Ruth Aline da Costa Nunes Silva", cpf: "407626298", emailPessoal: "ruth_acn@hotmail.com", emailCorporativo: "ruth.nsilva@goias.gov.br", status: "criado" },
    { id: "48", nome: "Sandra Virginia de Andrade Santos", cpf: "89018680168", emailPessoal: "sandravasantos@gmail.com", emailCorporativo: "sandra.asantos@goias.gov.br", status: "criado" },
    { id: "49", nome: "Shuleyma Sousa Gundim", cpf: "89788230172", emailPessoal: "shuleymasg@hotmail.com", emailCorporativo: "shuleyma.gundim@goias.gov.br", status: "criado" },
    { id: "50", nome: "Tatiane Almeida Gomes Sobrinho", cpf: "1988584183", emailPessoal: "tatianealmeida.pgt@hotmail.com", emailCorporativo: "tatiane.sobrinho@goias.gov.br", status: "criado" },
    { id: "51", nome: "Vania Maria Elias Neto Duarte", cpf: "28796926104", emailPessoal: "vaniaeliasneto@gmail.com", emailCorporativo: "vania.duarte@goias.gov.br", status: "criado" },
    { id: "52", nome: "Wellington Paiva de Carvalho", cpf: "4090744113", emailPessoal: "wellingtonpaiva165@gmail.com", emailCorporativo: "wellington.pcarvalho@goias.gov.br", status: "criado" },
    { id: "53", nome: "Dieneffer Caroline Ramos Silva", cpf: "70285338161", emailPessoal: "dieneffercaroline96@gmail.com", emailCorporativo: "dieneffer.silva@goias.gov.br", status: "criado" },
    { id: "54", nome: "Fernanda Lopes da Silva", cpf: "95796460153", emailPessoal: "fernandalops@hotmail.com", emailCorporativo: "fernanda.ldsilva@goias.gov.br", status: "criado" },
    { id: "55", nome: "Izadora Galvao Pereira", cpf: "3244956173", emailPessoal: "izadoragalvao@hotmail.com", emailCorporativo: "izadora.pereira@goias.gov.br", status: "criado" },
    { id: "56", nome: "Thairyni Oliveira Santos da Silva", cpf: "70299373177", emailPessoal: "thairyni.oli@outlook.com", emailCorporativo: "thairyni.silva@goias.gov.br", status: "criado" },
    { id: "57", nome: "Andre Filipe Costa Candido", cpf: "70073978167", emailPessoal: "costacandido447@gmail.com", emailCorporativo: "andre.candido@goias.gov.br", status: "criado" },
    { id: "58", nome: "Augusto Cezar Rodrigues Da Silva", cpf: "77533828968", emailPessoal: "acrsilva@live.com", emailCorporativo: "augusto.rsilva@goias.gov.br", status: "criado" },
    { id: "59", nome: "Brendany Bispo Cabral", cpf: "74912410187", emailPessoal: "brendanycabral@gmail.com", emailCorporativo: "brendany.cabral@goias.gov.br", status: "criado" },
    { id: "60", nome: "Cleuto Alves De Carvalho Filho", cpf: "3916272101", emailPessoal: "cleuto.cotec@gmail.com", emailCorporativo: "cleuto.carvalho@goias.gov.br", status: "criado" },
    { id: "61", nome: "Flavia Fernanda Sousa Santos", cpf: "6357217166", emailPessoal: "flaviafernanda2899@gmail.com", emailCorporativo: "flavia.fsantos@goias.gov.br", status: "criado" },
    { id: "62", nome: "Glazielle Da Costa Resende Nazare", cpf: "953648117", emailPessoal: "glazy_resende@hotmail.com", emailCorporativo: "glazielle.nazare@goias.gov.br", status: "criado" },
    { id: "63", nome: "Isabela Dallara Guimaraes Ribeiro", cpf: "70333004175", emailPessoal: "isabeladallara28@gmail.com", emailCorporativo: "isabela.ribeiro@goias.gov.br", status: "criado" },
    { id: "64", nome: "Pamella Mohara Silva", cpf: "4095905506", emailPessoal: "pamellamoharaanalista@gmail.com", emailCorporativo: "pamella.msilva@goias.gov.br", status: "criado" },
    { id: "65", nome: "Romulo Junior Nogueira Santos", cpf: "4654850147", emailPessoal: "romulojr14@gmail.com", emailCorporativo: "romulo.nsantos@goias.gov.br", status: "criado" },
    { id: "66", nome: "Sarah Karoline Teixeira De Sousa", cpf: "4277141170", emailPessoal: "sarah.karoline.cotec@gmail.com", emailCorporativo: "sarah.tsousa@goias.gov.br", status: "criado" },
    { id: "67", nome: "Talyson Felipe De Souza E Silva", cpf: "92829562291", emailPessoal: "talyson.felipess@gmail.com", emailCorporativo: "talyson.silva@goias.gov.br", status: "criado" },
    { id: "68", nome: "Wenderson Da Silva Vieira", cpf: "1961243105", emailPessoal: "wendersonsilvafadex@gmail.com", emailCorporativo: "wenderson.vieira@goias.gov.br", status: "criado" },
    { id: "69", nome: "Yasmin Neves Dourado", cpf: "9389409101", emailPessoal: "yasmindourado86@gmail.com", emailCorporativo: "yasmin.dourado@goias.gov.br", status: "criado" },
    { id: "70", nome: "Artur Rezende Martins", cpf: "6008047397", emailPessoal: "", emailCorporativo: "artur.martins@goias.gov.br", status: "criado" },
    { id: "71", nome: "Bruno Agrelio Ribeiro", cpf: "1241946647", emailPessoal: "", emailCorporativo: "bruno.agribeiro@goias.gov.br", status: "criado" },
    { id: "72", nome: "Danilo Martins de Oliveira", cpf: "4274484173", emailPessoal: "", emailCorporativo: "danilo.mdoliveira@goias.gov.br", status: "criado" },
    { id: "73", nome: "Fabricio Lima Cabral", cpf: "71279938234", emailPessoal: "", emailCorporativo: "fabricio.cabral@goias.gov.br", status: "criado" },
    { id: "74", nome: "Jose Alves de Sousa Junior", cpf: "4265333303", emailPessoal: "", emailCorporativo: "jose.asousa@goias.gov.br", status: "criado" },
    { id: "75", nome: "Roberto Sergio Jaldin Beckmann", cpf: "92960553187", emailPessoal: "", emailCorporativo: "roberto.beckmann@goias.gov.br", status: "criado" },
    { id: "76", nome: "Sandra Marinho da Costa", cpf: "86406213150", emailPessoal: "", emailCorporativo: "sandra.mcosta@goias.gov.br", status: "criado" },
    { id: "77", nome: "Thays Rodrigues Cardoso", cpf: "1975839110", emailPessoal: "", emailCorporativo: "thays.cardoso@goias.gov.br", status: "criado" },
    { id: "78", nome: "Natacha Ferreira Lorente", cpf: "38682789825", emailPessoal: "", emailCorporativo: "natacha.lorente@goias.gov.br", status: "criado" },
    { id: "79", nome: "Rayana Agrelio", cpf: "1050601351", emailPessoal: "", emailCorporativo: "rayana.agrelio@goias.gov.br", status: "criado" },
    { id: "80", nome: "Isabela da Cruz Pires", cpf: "04800888107", emailPessoal: "", emailCorporativo: "isabela.pires@goias.gov.br", status: "criado" },
    { id: "81", nome: "Ataualpa Veloso Roriz", cpf: "85136260115", emailPessoal: "", emailCorporativo: "atualpa.roriz@goias.gov.br", status: "criado" },
    { id: "82", nome: "Sandra Marinho da Costa", cpf: "86406213149", emailPessoal: "", emailCorporativo: "sandra.mcosta@goias.gov.br", status: "criado" },
    { id: "91", nome: "Ações Educacionais", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" },
    { id: "92", nome: "Ações Educacionais", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" },
    { id: "93", nome: "Ações Educacionais", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" },
    { id: "94", nome: "Ações Educacionais", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" },
    { id: "95", nome: "Ações Educacionais", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" },
    { id: "96", nome: "Ações Educacionais", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" },
    { id: "97", nome: "Administrativo e Financeiro", cpf: "", emailPessoal: "", emailCorporativo: "educacional.fadex@goias.gov.br", status: "Solicitado" }
];
